- menu_name: "Serviços"

- name: "Contato"
  url: "/contact/"
  title: "Contato"

- name: "RSS"
  url: "/feed.xml"
  title: "Inscreva-se no nosso RSS Feed"

- name: "Atom"
  url: "/atom.xml"
  title: "Inscreva-se no nosso Atom Feed"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap para Google Webmaster Tools"
